version: 2

multi-ecosystem-groups:
  dependencies:
    schedule:
      interval: weekly
    commit-message:
      prefix: chore(deps)

updates:
  - package-ecosystem: github-actions
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: dependencies

  - package-ecosystem: npm
    directory: /
    patterns:
      - "*"
    multi-ecosystem-group: dependencies
